services:
  backend:
    image: client:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    depends_on:
      - db_pg
      - redis
      - rabbitmq
    environment:
      SERVER_PORT: 8181
      DB_URL: jdbc:postgresql://db_pg:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SEED_ENABLED: true
      SEED_USERS_COUNT: 1000000
      SEED_MAX_FRIENDS_COUNT: 10
  db_pg:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'